### ISSUE TITLE
Heroku install?

### ISSUE THREAD

**Issue by alexriabtsev** [lybekk/offPIM#28]
I've just found offPIM and looks like it's the solution I've been looking for. Is there any way to deploy it to Heroku with "Deploy to Heroku" button?

**Comment by lybekk** [comment]
> I've just found offPIM and looks like it's the solution I've been looking for. Is there any way to deploy it to Heroku with "Deploy to Heroku" button?

Indeed it is :) Any HTTP server capable of serving static files can be used for serving it. 
Tested successfully on Apache, Express, Netlify, and even Python's built-in http.server

**Comment by alexriabtsev** [comment]
First i need to figure out howto do this ;)
I'm not a cool hacker indeed )))
