### ISSUE TITLE
Repeating taks?

### ISSUE THREAD

**Issue by alexriabtsev** [lybekk/offPIM#29]
I didn't find a way to create repeating task in offPIM. Is this feature available?

**Comment by lybekk** [comment]
> I didn't find a way to create repeating task in offPIM. Is this feature available?

I had plans for it, but moved on to other projects before being able to implement it properly. 
There are some design hurdles/considerations to make when designing repeating tasks when dealing with replication 😅

**Comment by alexriabtsev** [comment]
yeah, that's the reason good projects doesn't become great - we move on to other projects ;)

**Comment by lybekk** [comment]
True, indeed 😎
