### ISSUE TITLE
easy-pouchdb-server as another hosting option

### ISSUE THREAD

**Issue by acailly** [lybekk/offPIM#38]
Hi @lybekk ,

First, thank you for this work. 
I don't personally use it, but I try to build a side project that pretty much follows the same offline first + available on every platform approach, and this project is an example that I am not the only one following this path.

I use Cloudant a the remote, but I don't think it's an easy option, even for (lazy) devs.
Today I made a pouchdb-server config that you can remix on glitch easily, it is a 5min operation I think.

And I thought you might be interested 🙂 

Everything is here: https://github.com/acailly/easy-pouchdb-server

**Comment by lybekk** [comment]
This looks great! Clever move using Glitch :)
Cloudant is a tough sell. Especially when considering price.
Had my own attempt at something similar [offPIM Server](https://github.com/lybekk/offPIM-Server). One downside, it seems pouchdb-server isn't updated any more.

**Comment by acailly** [comment]
Oh I hadn't see offPIM server 🙂
I agree the fact that pouchdb server is not updated is a big downside, kind of restrict this option to experiments only 😕
I close this issue because it doesn't need any action.
