### ISSUE TITLE
Main website does not work

### ISSUE THREAD

**Issue by taha-mcp** [lybekk/offPIM#52]
[offpim.app](https://offpim.app/) does not work.

**Comment by lybekk** [comment]
I shut down the domain 'offpim.app', but the app is still available at [offpim.netlify.app](https://offpim.netlify.app). Sorry, I should probably have mentioned that somewhere.
The amount of traffic didn't justify keeping the domain up and running.

**Comment by lybekk** [comment]
620e3a4 - Updated broken links in README.md
